feat: allow wget or curl

diff --git a/neovim-manager b/neovim-manager
--- a/neovim-manager
+++ b/neovim-manager
@@ -250,11 +250,20 @@ neovim_manager_install_command() {
   archive="$name.$format"
   location="$share/nvim-$build"
 
+  http_client=${deps[http_client]}
+
   cd "$HOME"
 
-  wget --quiet "$github_url/$build/$archive"
+  case "$http_client" in
+    *wget)
+      "$http_client" --quiet "$github_url/$build/$archive"
+      ;;
+    *curl)
+      "$http_client" -sO "$github_url/$build/$archive"
+      ;;
+  esac
 
-  tar xzvf "$archive" &>/dev/null
+  tar xzf "$archive" &>/dev/null
 
   mkdir -p "$share"
 
@@ -458,18 +467,20 @@ neovim_manager_install_parse_requirements() {
 
   missing_deps=
 
-  if ! command -v wget >/dev/null 2>&1; then
-    printf "missing dependency: http_client\n" >&2
+  if ! command -v wget curl >/dev/null 2>&1; then
+    printf "missing dependency: http_client (wget/curl)\n" >&2
+    printf "%s\n\n" "Install 'wget' or 'curl' via system package manager" >&2
     missing_deps=1
   else
-    deps['http_client']="$(command -v wget | head -n1)"
+    deps['http_client']="$(command -v wget curl | head -n1)"
   fi
 
   if ! command -v tar >/dev/null 2>&1; then
-    printf "missing dependency: archive_tool\n" >&2
+    printf "missing dependency: tar\n" >&2
+    printf "%s\n\n" "Install 'tar' via system package manager" >&2
     missing_deps=1
   else
-    deps['archive_tool']="$(command -v tar | head -n1)"
+    deps['tar']="$(command -v tar | head -n1)"
   fi
 
   if [[ -n $missing_deps ]]; then
